//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovik
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationMaterial
    {
        public int ID { get; set; }
        public int OperationID { get; set; }
        public int MaterialID { get; set; }
        public int Count { get; set; }
        public int Nds { get; set; }
        public int Sum { get; set; }
    
        public virtual materials materials { get; set; }
        public virtual operations operations { get; set; }
    }
}
