//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovik
{
    using System;
    using System.Collections.Generic;
    
    public partial class operations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public operations()
        {
            this.OperationMaterial = new HashSet<OperationMaterial>();
        }
    
        public int ID { get; set; }
        public bool Type { get; set; }
        public string TypeStr { get; set; }
        public int Sum { get; set; }
        public string Status { get; set; }
        public string Provider { get; set; }
        public System.DateTime DateDoc { get; set; }
        public System.DateTime DateFact { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationMaterial> OperationMaterial { get; set; }
    }
}
